language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - cd docs/ && yarn install && yarn run deploy
deploy:
  provider: script
  skip_cleanup: true
  github_token: $GH_TOKEN
  on:
    branch: main