language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm run deploy
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: build
  on:
    branch: main