language: node_js
before_script:
 - npm install -g gatsby-cli
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script: 'true'
deploy:
  provider: script
  script: "npm run deploy"
  skip_cleanup: true
  github_token: $GH_TOKEN
  on:
    branch: main