language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
deploy:
  provider: pages
  script: cd docs/ && yarn install && yarn run deploy
  skip_cleanup: true
  github_token: $GH_TOKEN
  on:
    branch: main